#
# Makefile for the Macintosh-specific device drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_LS_APM_EMU)	+= apm_emu.o
obj-$(CONFIG_LS_XGI_MODE)	+= xgi_mode.o
obj-y                           += freebiosvga/
