#
# Makefile for the XGI framebuffer device driver
#

O_TARGET := XGIfb.o

obj-y    := XGI_main.o XGI_accel.o vb_init.o vb_setmode.o vb_util.o vb_ext.o	

# All of the (potential) objects that export symbols.

export-objs    :=  XGI_main.o

# Each configuration option enables a list of files.

obj-m    := $(O_TARGET)

include $(TOPDIR)/Rules.make

clean:
	rm -f core *.o
